debug: false
server:
  port: 8080
spring:
  http:
    encoding:
      charset: UTF-8
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-mm-dd
  datasource:
    url: jdbc:mysql://localhost:3306/zhaojie
    name: root
    driver-class-name: com.mysql.jdbc.Driver
    password: