debug: false
server:
  port: 8089
spring:
  http:
    encoding:
      charset: UTF-8
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-mm-dd
  datasource:
    url: jdbc:mysql://localhost:3306/zhaojie?characterEncoding=utf8
    name: root
    driver-class-name: com.mysql.jdbc.Driver
    password:
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml