debug: false
server:
  port: 8089

spring:
  http:
    encoding:
      charset: UTF-8
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-mm-dd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password:
  resources:
    static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml